<a href="https://colab.research.google.com/github/itsdakshjain/Python-Data-Science-Libraries/blob/main/NumPy/Concepts/Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [13]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a


array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [14]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[39, 78, 89, 47],
       [43, 74,  2, 59],
       [43, 95, 55, 93],
       [96, 49, 43, 44],
       [85, 18, 21, 44],
       [22, 93, 59, 90]])

In [15]:
np.sort(a)

array([ 6, 14, 16, 22, 22, 25, 31, 39, 42, 43, 48, 59, 60, 68, 88])

In [16]:
np.sort(a)[::-1]

array([88, 68, 60, 59, 48, 43, 42, 39, 31, 25, 22, 22, 16, 14,  6])

In [17]:
np.sort(b,axis=1)#0-column, 1-row

array([[39, 47, 78, 89],
       [ 2, 43, 59, 74],
       [43, 55, 93, 95],
       [43, 44, 49, 96],
       [18, 21, 44, 85],
       [22, 59, 90, 93]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [18]:
# code
np.append(a,200)

array([ 39,  16,  42,  31,  48,  88,   6,  14,  25,  68,  22,  43,  59,
        22,  60, 200])

In [19]:
b

array([[39, 78, 89, 47],
       [43, 74,  2, 59],
       [43, 95, 55, 93],
       [96, 49, 43, 44],
       [85, 18, 21, 44],
       [22, 93, 59, 90]])

In [20]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[39.        , 78.        , 89.        , 47.        ,  0.74256245],
       [43.        , 74.        ,  2.        , 59.        ,  0.98482172],
       [43.        , 95.        , 55.        , 93.        ,  0.21035865],
       [96.        , 49.        , 43.        , 44.        ,  0.23779916],
       [85.        , 18.        , 21.        , 44.        ,  0.57458107],
       [22.        , 93.        , 59.        , 90.        ,  0.824051  ]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [21]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [24]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [25]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [26]:
# (15,) is 1D  and (1,15)-2D
a
a.shape

(15,)

In [27]:
np.expand_dims(a,axis=0).shape #column me 15 hogya

(1, 15)

In [28]:
np.expand_dims(a,axis=1)#row me 15 hogya

array([[39],
       [16],
       [42],
       [31],
       [48],
       [88],
       [ 6],
       [14],
       [25],
       [68],
       [22],
       [43],
       [59],
       [22],
       [60]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [29]:
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [30]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 5,  9, 12, 14]),)

In [31]:
# replace all values > 50 with 0
np.where(a>50,0,a)  #np.where(condition,true,false) -syntax

array([39, 16, 42, 31, 48,  0,  6, 14, 25,  0, 22, 43,  0, 22,  0])

In [32]:
np.where(a%2 == 0,0,a)

array([39,  0,  0, 31,  0,  0,  0,  0, 25,  0,  0, 43, 59,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [33]:
# code
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [34]:
np.argmax(a)

5

In [35]:
b

array([[39, 78, 89, 47],
       [43, 74,  2, 59],
       [43, 95, 55, 93],
       [96, 49, 43, 44],
       [85, 18, 21, 44],
       [22, 93, 59, 90]])

In [36]:
np.argmax(b,axis=0) #col

array([3, 2, 0, 2])

In [37]:
np.argmax(b,axis=1) #row

array([2, 1, 1, 0, 0, 1])

In [38]:
# np.argmin
np.argmin(a)

6

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [39]:
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [40]:
np.cumsum(a)

array([ 39,  55,  97, 128, 176, 264, 270, 284, 309, 377, 399, 442, 501,
       523, 583])

In [41]:
b

array([[39, 78, 89, 47],
       [43, 74,  2, 59],
       [43, 95, 55, 93],
       [96, 49, 43, 44],
       [85, 18, 21, 44],
       [22, 93, 59, 90]])

In [42]:
np.cumsum(b,axis=1)

array([[ 39, 117, 206, 253],
       [ 43, 117, 119, 178],
       [ 43, 138, 193, 286],
       [ 96, 145, 188, 232],
       [ 85, 103, 124, 168],
       [ 22, 115, 174, 264]])

In [43]:
np.cumsum(b)

array([  39,  117,  206,  253,  296,  370,  372,  431,  474,  569,  624,
        717,  813,  862,  905,  949, 1034, 1052, 1073, 1117, 1139, 1232,
       1291, 1381])

In [44]:
# np.cumprod
np.cumprod(a)

array([                  39,                  624,                26208,
                     812448,             38997504,           3431780352,
                20590682112,         288269549568,        7206738739200,
            490058234265600,    10781281153843200,   463595089615257600,
        8905366213590646784, -6996128111810838528,  4507426986669375488])

In [45]:
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [46]:
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [47]:
print(np.percentile(a,0))
print(np.percentile(a,50))
np.percentile(a,100)

6.0
39.0


88.0

In [48]:
np.median(a) # =50 percentile

39.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [49]:
# code
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [50]:
np.histogram(a,bins=[0,50,100])

(array([11,  4]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [52]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [53]:
# code
a


array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [54]:
items = [10,20,30,40,50,60,70,80,90,100]

np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [55]:
a[np.isin(a,items)]

array([60])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [56]:
# code
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [57]:
np.flip(a)

array([60, 22, 59, 43, 22, 68, 25, 14,  6, 88, 48, 31, 42, 16, 39])

In [58]:
b

array([[39, 78, 89, 47],
       [43, 74,  2, 59],
       [43, 95, 55, 93],
       [96, 49, 43, 44],
       [85, 18, 21, 44],
       [22, 93, 59, 90]])

In [59]:
np.flip(b)  # both columns , row flip

array([[90, 59, 93, 22],
       [44, 21, 18, 85],
       [44, 43, 49, 96],
       [93, 55, 95, 43],
       [59,  2, 74, 43],
       [47, 89, 78, 39]])

In [60]:
np.flip(b,axis=1)  # row flip

array([[47, 89, 78, 39],
       [59,  2, 74, 43],
       [93, 55, 95, 43],
       [44, 43, 49, 96],
       [44, 21, 18, 85],
       [90, 59, 93, 22]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [61]:
# code
a

array([39, 16, 42, 31, 48, 88,  6, 14, 25, 68, 22, 43, 59, 22, 60])

In [62]:
np.put(a,[0,1],[110,530])

In [63]:
a   # permanently changes the array

array([110, 530,  42,  31,  48,  88,   6,  14,  25,  68,  22,  43,  59,
        22,  60])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [64]:
# code
a

array([110, 530,  42,  31,  48,  88,   6,  14,  25,  68,  22,  43,  59,
        22,  60])

In [65]:
np.delete(a,[0,2,4])  # dlt is temporary

array([530,  31,  88,   6,  14,  25,  68,  22,  43,  59,  22,  60])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [66]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
np.intersect1d(m,n)

array([3, 4, 5])

In [69]:
np.setdiff1d(n,m)

array([6, 7])

In [71]:
np.setxor1d(m,n)  # not ~(a intersection b)

array([1, 2, 6, 7])

In [77]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [78]:
# code
a

array([110, 530,  42,  31,  48,  88,   6,  14,  25,  68,  22,  43,  59,
        22,  60])

In [ ]:
np.clip(a,a_min=25,a_max=75) # 110 changed to 75 limit and 2 to 25

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes        *interview*

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals